### ISSUE TITLE
Incorrect Bin Names

### ISSUE THREAD

**Issue by Mestalbet** [jabiru/binr#2]
The bin names for binct do not match the binlo and binhi values in the output. 
`x <- rep(c(1:10,20,31:40), c(rep(1, 10), 100, rep(1,10)))`
`cuts <- bins(x, target.bins = 3, minpts = 10)`
`cuts$binct`
` [1, 10] [20, 20] [31, 40] `
`      10      100       10 `
`cuts$binlo`
`[1]  1 11 12`
`cuts$binhi`
`[1] 10 11 21`

**Comment by sizrailev** [comment]
Hi @Mestalbet - thanks for noticing that the documentation is inaccurate. The values in `cuts$binlo` and `cuts$binhi` are the indices into the `cuts$xval` rather than values. The values can be obtained using `cuts$xval[cuts$binlo]`

Docs will be fixed in the next version.
